package top.guhanjie.wine.model;

import java.util.Date;

public class Bannar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.id
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.img
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.title
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.description
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.idx
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    private Integer idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.item_id
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.create_time
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.update_time
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.id
     *
     * @return the value of bannar.id
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.id
     *
     * @param id the value for bannar.id
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.img
     *
     * @return the value of bannar.img
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.img
     *
     * @param img the value for bannar.img
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.title
     *
     * @return the value of bannar.title
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.title
     *
     * @param title the value for bannar.title
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.description
     *
     * @return the value of bannar.description
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.description
     *
     * @param description the value for bannar.description
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.idx
     *
     * @return the value of bannar.idx
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.idx
     *
     * @param idx the value for bannar.idx
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.item_id
     *
     * @return the value of bannar.item_id
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.item_id
     *
     * @param itemId the value for bannar.item_id
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.create_time
     *
     * @return the value of bannar.create_time
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.create_time
     *
     * @param createTime the value for bannar.create_time
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.update_time
     *
     * @return the value of bannar.update_time
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.update_time
     *
     * @param updateTime the value for bannar.update_time
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}