package top.guhanjie.wine.model;

import java.util.Date;

public class Bannar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.index
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Short index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.item_id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.create_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bannar.update_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.id
     *
     * @return the value of bannar.id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.id
     *
     * @param id the value for bannar.id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.index
     *
     * @return the value of bannar.index
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Short getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.index
     *
     * @param index the value for bannar.index
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setIndex(Short index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.item_id
     *
     * @return the value of bannar.item_id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.item_id
     *
     * @param itemId the value for bannar.item_id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.create_time
     *
     * @return the value of bannar.create_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.create_time
     *
     * @param createTime the value for bannar.create_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bannar.update_time
     *
     * @return the value of bannar.update_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bannar.update_time
     *
     * @param updateTime the value for bannar.update_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}