package top.guhanjie.wine.model;

import java.math.BigDecimal;
import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.icon
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.detail
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.category_id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.normal_price
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private BigDecimal normalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.vip_price
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private BigDecimal vipPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.back_points
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Integer backPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.sales
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Integer sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.status
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img1
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img2
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img3
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img4
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img5
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img6
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img7
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img8
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img9
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img10
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private String img10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.create_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.update_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.icon
     *
     * @return the value of item.icon
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.icon
     *
     * @param icon the value for item.icon
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.detail
     *
     * @return the value of item.detail
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.detail
     *
     * @param detail the value for item.detail
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.category_id
     *
     * @return the value of item.category_id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.category_id
     *
     * @param categoryId the value for item.category_id
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.normal_price
     *
     * @return the value of item.normal_price
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public BigDecimal getNormalPrice() {
        return normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.normal_price
     *
     * @param normalPrice the value for item.normal_price
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setNormalPrice(BigDecimal normalPrice) {
        this.normalPrice = normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.vip_price
     *
     * @return the value of item.vip_price
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public BigDecimal getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.vip_price
     *
     * @param vipPrice the value for item.vip_price
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setVipPrice(BigDecimal vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.back_points
     *
     * @return the value of item.back_points
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Integer getBackPoints() {
        return backPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.back_points
     *
     * @param backPoints the value for item.back_points
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setBackPoints(Integer backPoints) {
        this.backPoints = backPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sales
     *
     * @return the value of item.sales
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sales
     *
     * @param sales the value for item.sales
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.status
     *
     * @return the value of item.status
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.status
     *
     * @param status the value for item.status
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img1
     *
     * @return the value of item.img1
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg1() {
        return img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img1
     *
     * @param img1 the value for item.img1
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg1(String img1) {
        this.img1 = img1 == null ? null : img1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img2
     *
     * @return the value of item.img2
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg2() {
        return img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img2
     *
     * @param img2 the value for item.img2
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg2(String img2) {
        this.img2 = img2 == null ? null : img2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img3
     *
     * @return the value of item.img3
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg3() {
        return img3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img3
     *
     * @param img3 the value for item.img3
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg3(String img3) {
        this.img3 = img3 == null ? null : img3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img4
     *
     * @return the value of item.img4
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg4() {
        return img4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img4
     *
     * @param img4 the value for item.img4
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg4(String img4) {
        this.img4 = img4 == null ? null : img4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img5
     *
     * @return the value of item.img5
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg5() {
        return img5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img5
     *
     * @param img5 the value for item.img5
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg5(String img5) {
        this.img5 = img5 == null ? null : img5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img6
     *
     * @return the value of item.img6
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg6() {
        return img6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img6
     *
     * @param img6 the value for item.img6
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg6(String img6) {
        this.img6 = img6 == null ? null : img6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img7
     *
     * @return the value of item.img7
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg7() {
        return img7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img7
     *
     * @param img7 the value for item.img7
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg7(String img7) {
        this.img7 = img7 == null ? null : img7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img8
     *
     * @return the value of item.img8
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg8() {
        return img8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img8
     *
     * @param img8 the value for item.img8
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg8(String img8) {
        this.img8 = img8 == null ? null : img8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img9
     *
     * @return the value of item.img9
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg9() {
        return img9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img9
     *
     * @param img9 the value for item.img9
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg9(String img9) {
        this.img9 = img9 == null ? null : img9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img10
     *
     * @return the value of item.img10
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public String getImg10() {
        return img10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img10
     *
     * @param img10 the value for item.img10
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setImg10(String img10) {
        this.img10 = img10 == null ? null : img10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.create_time
     *
     * @return the value of item.create_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.create_time
     *
     * @param createTime the value for item.create_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_time
     *
     * @return the value of item.update_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_time
     *
     * @param updateTime the value for item.update_time
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}