package top.guhanjie.wine.model;

import java.util.Date;

public class LotteryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_info.id
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_info.lottery_code
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    private String lotteryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_info.round
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    private String round;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_info.type
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_info.create_time
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_info.update_time
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_info.id
     *
     * @return the value of lottery_info.id
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_info.id
     *
     * @param id the value for lottery_info.id
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_info.lottery_code
     *
     * @return the value of lottery_info.lottery_code
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public String getLotteryCode() {
        return lotteryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_info.lottery_code
     *
     * @param lotteryCode the value for lottery_info.lottery_code
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public void setLotteryCode(String lotteryCode) {
        this.lotteryCode = lotteryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_info.round
     *
     * @return the value of lottery_info.round
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public String getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_info.round
     *
     * @param round the value for lottery_info.round
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public void setRound(String round) {
        this.round = round == null ? null : round.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_info.type
     *
     * @return the value of lottery_info.type
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_info.type
     *
     * @param type the value for lottery_info.type
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_info.create_time
     *
     * @return the value of lottery_info.create_time
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_info.create_time
     *
     * @param createTime the value for lottery_info.create_time
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_info.update_time
     *
     * @return the value of lottery_info.update_time
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_info.update_time
     *
     * @param updateTime the value for lottery_info.update_time
     *
     * @mbggenerated Sun Apr 15 17:33:13 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}