package top.guhanjie.wine.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.contactor
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private String contactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.phone
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.remark
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.source
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private String payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_type
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_status
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.contactor
     *
     * @return the value of order.contactor
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.contactor
     *
     * @param contactor the value for order.contactor
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setContactor(String contactor) {
        this.contactor = contactor == null ? null : contactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.phone
     *
     * @return the value of order.phone
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.phone
     *
     * @param phone the value for order.phone
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.remark
     *
     * @return the value of order.remark
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.remark
     *
     * @param remark the value for order.remark
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.source
     *
     * @return the value of order.source
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.source
     *
     * @param source the value for order.source
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_id
     *
     * @return the value of order.pay_id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_id
     *
     * @param payId the value for order.pay_id
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_type
     *
     * @return the value of order.pay_type
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_type
     *
     * @param payType the value for order.pay_type
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_status
     *
     * @return the value of order.pay_status
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_status
     *
     * @param payStatus the value for order.pay_status
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_time
     *
     * @return the value of order.pay_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_time
     *
     * @param payTime the value for order.pay_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbggenerated Sun Aug 13 16:42:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Class Name:    PayStatusEnum<br/>
     * <b>支付状态:    </b>
     * <ul>
     * <li>0：未支付，</li>
     * <li>1：支付成功，</li>
     * <li>2：支付失败，</li>
     * <li>3：转入退款，</li>
     * <li>4：已关闭，</li>
     * <li>5：已撤销（刷卡支付），</li>
     * <li>6： 用户支付中</li>
     * </ul>
     */
    public static enum PayStatusEnum {

        NOTPAY(0, "未支付"),
        SUCCESS(1, "支付成功"),
        PAYERROR(2, "支付失败"),
        REFUND(3, "转入退款"),
        CLOSED(4, "已关闭"),
        REVOKED(5, "已撤销（刷卡支付）"),
        USERPAYING(6, "用户支付中");
        
        private int code;
        private String desc;
        
        private PayStatusEnum(int code, String desc) {
            this.code = code;
            this.desc = desc;
        }
        
        public int code() {
            return code;
        }
        
        public String desc() {
            return desc;
        }
    }
    

    /**
     * Class Name:    PayTypeEnum<br/>
     * <b>支付类型:    </b>
     * <ul>
     * <li>0：微信支付，</li>
     * <li>1：现金</li>
     * </ul>
     */
    public static enum PayTypeEnum {

        WEIXIN(0, "微信支付"),
        CASH(1, "现金支付");
        
        private int code;
        private String desc;
        
        private PayTypeEnum(int code, String desc) {
            this.code = code;
            this.desc = desc;
        }
        
        public int code() {
            return code;
        }
        
        public String desc() {
            return desc;
        }
    }
    
    /**
     * Class Name:    StatusEnum<br/>
     * <b>订单状态，采用位表示法，第1-2位：是否下单成功，第3-4位：是否开始送货，第5-6位：是否支付完成]</b>
     */
    public static enum StatusEnum {
        //位表示法  
    //  private static final short PUT_ORDER = 0x01;        //下单与（否）
    //  private static final short CANCEL_ORDER = 0x02;     //取消与（否）
    //  private static final short START_SEND = 0x04;       //开始送货与（否）
    //  private static final short FINISH_ORDER = 0x08;     //完成与（否）
    //  private static final short PAY_ORDER = 0x10;        //支付与（否）
        
        NEW(0x01, "新建订单"),           //1
        CANCEL((0x01<<2 | 0x01), "取消订单"),    //3
        SENDING((0x01<<3 | 0x01), "开始送货"),   //5
        FINISH((0x01<<4 | 0x01<<3 | 0x01), "送货完成"),        //13
        PAYED((0x01<<5 | 0x01<<4 | 0x01<<3 | 0x01), "支付完成");     //29
        
        private int code;
        private String desc;
        
        private StatusEnum(int code, String desc) {
            this.code = code;
            this.desc = desc;
        }
        
        public int code() {
            return code;
        }
        
        public String desc() {
            return desc;
        }
    }

}