package top.guhanjie.wine.model;

import java.util.Date;

public class PointDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.points
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.type
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.user_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.item_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.promotee_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer promoteeId;
    
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.create_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.update_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.id
     *
     * @return the value of point_detail.id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.id
     *
     * @param id the value for point_detail.id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.points
     *
     * @return the value of point_detail.points
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.points
     *
     * @param points the value for point_detail.points
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.type
     *
     * @return the value of point_detail.type
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.type
     *
     * @param type the value for point_detail.type
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.user_id
     *
     * @return the value of point_detail.user_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.user_id
     *
     * @param userId the value for point_detail.user_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.orderId
     *
     * @return the value of point_detail.orderId
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.orderId
     *
     * @param itemId the value for point_detail.orderId
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.promotee_id
     *
     * @return the value of point_detail.promotee_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getPromoteeId() {
        return promoteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.promotee_id
     *
     * @param promoteeId the value for point_detail.promotee_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setPromoteeId(Integer promoteeId) {
        this.promoteeId = promoteeId;
    }

    public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.create_time
     *
     * @return the value of point_detail.create_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.create_time
     *
     * @param createTime the value for point_detail.create_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.update_time
     *
     * @return the value of point_detail.update_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.update_time
     *
     * @param updateTime the value for point_detail.update_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    /**
     * Class Name:    TypeEnum<br/>
     * <b>积分来源类型:    </b>
     * <ul>
     * <li>+：加分，</li>
     * <li>-：减分</li>
     * </ul>
     */
    public static enum TypeEnum {

        ADD("+", "加分"),
        SUB("-", "减分");
        
        private String code;
        private String desc;
        
        private TypeEnum(String code, String desc) {
            this.code = code;
            this.desc = desc;
        }
        
        public String code() {
            return code;
        }
        
        public String desc() {
            return desc;
        }
    }
    
    /**
     * Class Name:    RemarkEnum<br/>
     * <b>积分明细备注:    </b>
     * <ul>
     * <li>+：加分，</li>
     * <li>-：减分</li>
     * </ul>
     */
    public static enum RemarkEnum {

        USER_SIGN_UP("会员注册奖励"),
        AGENT_RETURN("代理商提成奖励"),
        ADD_BY_ADMIN("管理员加分"),
        SUB_BY_ADMIN("管理员减分"),
        REFUND("订单取消积分返还"),
        CONSUME("积分消费");
        
        private String remark;
        
        private RemarkEnum(String remark) {
            this.remark = remark;
        }
        
        public String remark() {
            return remark;
        }
    }
}