package top.guhanjie.wine.model;

import java.util.Date;

public class PointDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.points
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.type
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.user_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.item_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.promotee_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Integer promoteeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.create_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_detail.update_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.id
     *
     * @return the value of point_detail.id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.id
     *
     * @param id the value for point_detail.id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.points
     *
     * @return the value of point_detail.points
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.points
     *
     * @param points the value for point_detail.points
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.type
     *
     * @return the value of point_detail.type
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.type
     *
     * @param type the value for point_detail.type
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.user_id
     *
     * @return the value of point_detail.user_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.user_id
     *
     * @param userId the value for point_detail.user_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.item_id
     *
     * @return the value of point_detail.item_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.item_id
     *
     * @param itemId the value for point_detail.item_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.promotee_id
     *
     * @return the value of point_detail.promotee_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Integer getPromoteeId() {
        return promoteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.promotee_id
     *
     * @param promoteeId the value for point_detail.promotee_id
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setPromoteeId(Integer promoteeId) {
        this.promoteeId = promoteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.create_time
     *
     * @return the value of point_detail.create_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.create_time
     *
     * @param createTime the value for point_detail.create_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.update_time
     *
     * @return the value of point_detail.update_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.update_time
     *
     * @param updateTime the value for point_detail.update_time
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}