package top.guhanjie.wine.model;

import java.lang.reflect.InvocationTargetException;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.commons.beanutils.PropertyUtils;

public class RushItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.id
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.name
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.icon
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.detail
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.category_id
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.normal_price
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private BigDecimal normalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.vip_price
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private BigDecimal vipPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.back_points
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Integer backPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.buyers
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Integer buyers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.counts
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.status
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Integer status;
    
    private String lotteryCode;
    private String round;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.start_tiem
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Date startTiem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.end_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.images
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private String titleImgs;
    private String detailImgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.create_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rush_item.update_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.id
     *
     * @return the value of rush_item.id
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.id
     *
     * @param id the value for rush_item.id
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.name
     *
     * @return the value of rush_item.name
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.name
     *
     * @param name the value for rush_item.name
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.icon
     *
     * @return the value of rush_item.icon
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.icon
     *
     * @param icon the value for rush_item.icon
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.detail
     *
     * @return the value of rush_item.detail
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.detail
     *
     * @param detail the value for rush_item.detail
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.category_id
     *
     * @return the value of rush_item.category_id
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.category_id
     *
     * @param categoryId the value for rush_item.category_id
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.normal_price
     *
     * @return the value of rush_item.normal_price
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public BigDecimal getNormalPrice() {
        return normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.normal_price
     *
     * @param normalPrice the value for rush_item.normal_price
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setNormalPrice(BigDecimal normalPrice) {
        this.normalPrice = normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.vip_price
     *
     * @return the value of rush_item.vip_price
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public BigDecimal getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.vip_price
     *
     * @param vipPrice the value for rush_item.vip_price
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setVipPrice(BigDecimal vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.back_points
     *
     * @return the value of rush_item.back_points
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Integer getBackPoints() {
        return backPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.back_points
     *
     * @param backPoints the value for rush_item.back_points
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setBackPoints(Integer backPoints) {
        this.backPoints = backPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.buyers
     *
     * @return the value of rush_item.buyers
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Integer getBuyers() {
        return buyers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.buyers
     *
     * @param buyers the value for rush_item.buyers
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setBuyers(Integer buyers) {
        this.buyers = buyers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.counts
     *
     * @return the value of rush_item.counts
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.counts
     *
     * @param counts the value for rush_item.counts
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.status
     *
     * @return the value of rush_item.status
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.status
     *
     * @param status the value for rush_item.status
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    public String getLotteryCode() {
    	return this.lotteryCode;
    }
    
    public void setLotteryCode(String lotteryCode) {
        this.lotteryCode = lotteryCode;
    }
    
    public String getRound() {
    	return this.round;
    }
    
    public void setRound(String round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.start_tiem
     *
     * @return the value of rush_item.start_tiem
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Date getStartTiem() {
        return startTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.start_tiem
     *
     * @param startTiem the value for rush_item.start_tiem
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setStartTiem(Date startTiem) {
        this.startTiem = startTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.end_time
     *
     * @return the value of rush_item.end_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.end_time
     *
     * @param endTime the value for rush_item.end_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.images
     *
     * @return the value of rush_item.images
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public String getTitleImgs() {
        return titleImgs;
    }
    
    public String getDetailImgs() {
        return detailImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.images
     *
     * @param images the value for rush_item.images
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setTitleImgs(String titleImgs) {
        this.titleImgs = titleImgs == null ? null : titleImgs.trim();
    }
    
    public void setDetailImgs(String detailImgs) {
        this.detailImgs = detailImgs == null ? null : detailImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.create_time
     *
     * @return the value of rush_item.create_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.create_time
     *
     * @param createTime the value for rush_item.create_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rush_item.update_time
     *
     * @return the value of rush_item.update_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rush_item.update_time
     *
     * @param updateTime the value for rush_item.update_time
     *
     * @mbggenerated Sun Aug 20 16:15:40 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Class Name:    StatusEnum<br/>
     * <b>支付状态:    </b>
     * <ul>
     * <li>1：进行中，</li>
     * <li>2：未开始，</li>
     * <li>3：已结束</li>
     * </ul>
     */
    public static enum StatusEnum {

        PROCESSING(1, "进行中"),
        NOT_STARTED(2, "未开始"),
        OVER(3, "已结束"),
        DELETED(4, "已删除");
        
        private int code;
        private String desc;
        
        private StatusEnum(int code, String desc) {
            this.code = code;
            this.desc = desc;
        }
        
        public int code() {
            return code;
        }
        
        public String desc() {
            return desc;
        }
    }

    //------------------------- custom add -----------------------------
    private int count;	//used in order buy

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}
	
	public RushItem deepCopy() {
		RushItem copy = new RushItem();
		try {
			PropertyUtils.copyProperties(copy, this);
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return copy;
	}
	
	private List<RushLottery> rushLotterys;
	
	public void setRushLotterys(List<RushLottery> rushLotterys) {
		this.rushLotterys = rushLotterys;
	}
	
	public List<RushLottery> getRushLotterys() {
		return this.rushLotterys;
	}
	
	private boolean won;
	public void setWon(boolean won) {
		this.won = won;
	}
	public boolean isWon() {
		return this.won;
	}
	//------------------------- custom add -----------------------------

}