package top.guhanjie.wine.model;

import java.math.BigDecimal;
import java.util.Date;

public class VipItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.id
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.name
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.icon
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.detail
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.category_id
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.normal_price
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private BigDecimal normalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.vip_price
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private BigDecimal vipPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.back_points
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private Integer backPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.sales
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private Integer sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.status
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.title_imgs
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private String titleImgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.detail_imgs
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private String detailImgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.create_time
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_item.update_time
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.id
     *
     * @return the value of vip_item.id
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.id
     *
     * @param id the value for vip_item.id
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.name
     *
     * @return the value of vip_item.name
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.name
     *
     * @param name the value for vip_item.name
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.icon
     *
     * @return the value of vip_item.icon
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.icon
     *
     * @param icon the value for vip_item.icon
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.detail
     *
     * @return the value of vip_item.detail
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.detail
     *
     * @param detail the value for vip_item.detail
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.category_id
     *
     * @return the value of vip_item.category_id
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.category_id
     *
     * @param categoryId the value for vip_item.category_id
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.normal_price
     *
     * @return the value of vip_item.normal_price
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public BigDecimal getNormalPrice() {
        return normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.normal_price
     *
     * @param normalPrice the value for vip_item.normal_price
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setNormalPrice(BigDecimal normalPrice) {
        this.normalPrice = normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.vip_price
     *
     * @return the value of vip_item.vip_price
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public BigDecimal getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.vip_price
     *
     * @param vipPrice the value for vip_item.vip_price
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setVipPrice(BigDecimal vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.back_points
     *
     * @return the value of vip_item.back_points
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public Integer getBackPoints() {
        return backPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.back_points
     *
     * @param backPoints the value for vip_item.back_points
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setBackPoints(Integer backPoints) {
        this.backPoints = backPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.sales
     *
     * @return the value of vip_item.sales
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.sales
     *
     * @param sales the value for vip_item.sales
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.status
     *
     * @return the value of vip_item.status
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.status
     *
     * @param status the value for vip_item.status
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.title_imgs
     *
     * @return the value of vip_item.title_imgs
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public String getTitleImgs() {
        return titleImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.title_imgs
     *
     * @param titleImgs the value for vip_item.title_imgs
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setTitleImgs(String titleImgs) {
        this.titleImgs = titleImgs == null ? null : titleImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.detail_imgs
     *
     * @return the value of vip_item.detail_imgs
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public String getDetailImgs() {
        return detailImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.detail_imgs
     *
     * @param detailImgs the value for vip_item.detail_imgs
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setDetailImgs(String detailImgs) {
        this.detailImgs = detailImgs == null ? null : detailImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.create_time
     *
     * @return the value of vip_item.create_time
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.create_time
     *
     * @param createTime the value for vip_item.create_time
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_item.update_time
     *
     * @return the value of vip_item.update_time
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_item.update_time
     *
     * @param updateTime the value for vip_item.update_time
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}