package top.guhanjie.wine.mapper;

import top.guhanjie.wine.model.Bannar;

public interface BannarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int insert(Bannar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int insertSelective(Bannar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    Bannar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int updateByPrimaryKeySelective(Bannar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int updateByPrimaryKey(Bannar record);
}