package top.guhanjie.wine.mapper;

import java.util.List;

import top.guhanjie.wine.model.Bannar;

public interface BannarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    int insert(Bannar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    int insertSelective(Bannar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    Bannar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    int updateByPrimaryKeySelective(Bannar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bannar
     *
     * @mbggenerated Sun Aug 06 16:29:23 CST 2017
     */
    int updateByPrimaryKey(Bannar record);
    
    //~~~~~~~~~~~~~~~~~ custom add ~~~~~~~~~~~~~~~~~~
    List<Bannar> selectAll();
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
}