package top.guhanjie.wine.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.guhanjie.wine.model.Item;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Aug 20 16:27:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Aug 20 16:27:11 CST 2017
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Aug 20 16:27:11 CST 2017
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Aug 20 16:27:11 CST 2017
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Aug 20 16:27:11 CST 2017
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Aug 20 16:27:11 CST 2017
     */
    int updateByPrimaryKey(Item record);
    
    //~~~~~~~~~~~~~~~~~ custom add ~~~~~~~~~~~~~~~~~~
    Item selectById(int id);
    List<Item> selectByCategory(int category);
    int addSales(@Param("itemid")Integer itemid, @Param("sales")Integer sales);
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
}