package top.guhanjie.wine.mapper;

import top.guhanjie.wine.model.PointDetail;

public interface PointDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    int insert(PointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    int insertSelective(PointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    PointDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    int updateByPrimaryKeySelective(PointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbggenerated Tue Jun 06 14:00:41 CST 2017
     */
    int updateByPrimaryKey(PointDetail record);
}