package top.guhanjie.wine.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.guhanjie.wine.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 06 00:54:08 CST 2017
     */
    int updateByPrimaryKey(User record);

    //------------------------- custom add -----------------------------
    User selectLikeName(String name);
    User selectByOpenId(String openid);
    
    User selectByPhone(String phone);
    
    List<User> selectBySourceId(Integer id);
    
    int addPoints(@Param("userid")Integer userid, @Param("points")Integer points);
    int subPoints(@Param("userid")Integer userid, @Param("points")Integer points);
    //--------------------------------------------------------------------
}