package top.guhanjie.wine.mapper;

import top.guhanjie.wine.model.VipItem;

public interface VipItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_item
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_item
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    int insert(VipItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_item
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    int insertSelective(VipItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_item
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    VipItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_item
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    int updateByPrimaryKeySelective(VipItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_item
     *
     * @mbggenerated Mon Sep 18 09:01:23 CST 2017
     */
    int updateByPrimaryKey(VipItem record);
}